---
name: parrottools

on: [push]

jobs:
  tests:
    name: Python ${{ matrix.python-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: make install
      - name: "Run tests - ${{ matrix.python-version }}"
        run: make test
      - name: "Run lint - ${{ matrix.python-version }}"
        run: make lint
